### ISSUE TITLE
i might just be dumb

### ISSUE THREAD

**Issue by dabittydab** [Najatski/dipper#8]
the .pyw does not open on my pc

**Comment by Najatski** [comment]
Did you run the install dependencies file? Oh, and Python _is_ installed right?

**Comment by dabittydab** [comment]
yes i did both

**Comment by dabittydab** [comment]
is it posible to make it an exe, i still cant make it work

**Comment by Najatski** [comment]
> is it posible to make it an exe, i still cant make it work

I've tried, though it has been a few weeks. School isn't helping.. I really need to come back to working on this stuff at some 
point.

You're not really giving me much info to work with so I'll have a hard time helping.
Open Python IDLE (Win + S -> "IDLE"). File > Open, and browse for the .pyw file.
Run it, and IDLE _should_ tell you what's up.

Let me know what it says.

**Comment by dabittydab** [comment]
Traceback (most recent call last):
  File "C:\Users\Admn\Downloads\DipperGUI.pyw", line 1, in <module>
    from pyvjoystick import vjoy as pyvjoy
ModuleNotFoundError: No module named 'pyvjoystick'

**Comment by Najatski** [comment]
> ModuleNotFoundError: No module named 'pyvjoystick'

There's the issue.

Here's how to fix it:
1. Open PowerShell.
2. Type `pip install pyvjoystick` and hit enter.
3. Wait for it to install.
4. Run the script as normal again.

Let me know if this works.

**Comment by dabittydab** [comment]
it worked!!!!!!!!!!!! thnks

**Comment by Najatski** [comment]
no problem
